@PORT=8000
@URL=http://18.231.62.156:8000/

# @name PostDataVP
POST  {{URL}}home HTTP/1.1
content-type: application/json

{
    "vazao": 20,
    "pressao": 20
}

###

# @name GetDataVP
GET {{URL}}home HTTP/1.1
content-type: application/json

###

# @name DeleteDataVP
DELETE {{URL}}home/10707 HTTP/1.1
content-type: application/json